#!/usr/bin/env bash
# Bash script to Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
rdt="location /redirect_me {\\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n}"
sudo sed -i "30i $rdt" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/pnf_404.html
err="error_page 404 /pnf_404.html;\nlocation = /pnf_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "33i $err" /etc/nginx/sites-available/default
sudo service nginx restart