#!/usr/bin/env bash
# running apache on designated container and to return a page
# containing Hello Holberton when querying the root of it

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start