#!/bin/bash
# This script gracefully reloads Gunicorn without downtime

# Get the PID of the Gunicorn master process
PID=$(ps aux | grep '[g]unicorn' | awk '{print $2}')

# Send the HUP signal to the Gunicorn master process to reload it gracefully
if [ -n "$PID" ]; then
    kill -HUP $PID
    echo "Gunicorn has been gracefully reloaded."
else
    echo "Gunicorn master process not found."
fi
